const profile = {
	id: '103478300',
	nodeId: 'U_kgDOBir0HA',
	displayName: 'Aleksandr A',
	username: 'Art-San',
	profileUrl: 'https://github.com/Art-San',
	photos: [{ value: 'https://avatars.githubusercontent.com/u/103478300?v=4' }],
	provider: 'github',
	_raw: '{"login":"Art-San","id":103478300,"node_id":"U_kgDOBir0HA","avatar_url":"https://avatars.githubusercontent.com/u/103478300?v=4","gravatar_id":"","url":"https://api.github.com/users/Art-San","html_url":"https://github.com/Art-San","followers_url":"https://api.github.com/users/Art-San/followers","following_url":"https://api.github.com/users/Art-San/following{/other_user}","gists_url":"https://api.github.com/users/Art-San/gists{/gist_id}","starred_url":"https://api.github.com/users/Art-San/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Art-San/subscriptions","organizations_url":"https://api.github.com/users/Art-San/orgs","repos_url":"https://api.github.com/users/Art-San/repos","events_url":"https://api.github.com/users/Art-San/events{/privacy}","received_events_url":"https://api.github.com/users/Art-San/received_events","type":"User","site_admin":false,"name":"Aleksandr A","company":null,"blog":"","location":null,"email":null,"hireable":null,"bio":null,"twitter_username":null,"public_repos":89,"public_gists":0,"followers":0,"following":0,"created_at":"2022-04-12T04:02:44Z","updated_at":"2024-03-20T09:15:39Z"}',
	_json: {
		login: 'Art-San',
		id: 103478300,
		node_id: 'U_kgDOBir0HA',
		avatar_url: 'https://avatars.githubusercontent.com/u/103478300?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/Art-San',
		html_url: 'https://github.com/Art-San',
		followers_url: 'https://api.github.com/users/Art-San/followers',
		following_url:
			'https://api.github.com/users/Art-San/following{/other_user}',
		gists_url: 'https://api.github.com/users/Art-San/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/Art-San/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/Art-San/subscriptions',
		organizations_url: 'https://api.github.com/users/Art-San/orgs',
		repos_url: 'https://api.github.com/users/Art-San/repos',
		events_url: 'https://api.github.com/users/Art-San/events{/privacy}',
		received_events_url: 'https://api.github.com/users/Art-San/received_events',
		type: 'User',
		site_admin: false,
		name: 'Aleksandr A',
		company: null,
		blog: '',
		location: null,
		email: null,
		hireable: null,
		bio: null,
		twitter_username: null,
		public_repos: 89,
		public_gists: 0,
		followers: 0,
		following: 0,
		created_at: '2022-04-12T04:02:44Z',
		updated_at: '2024-03-20T09:15:39Z',
	},
	emails: [{ value: 'artsan.mcc@gmail.com' }],
}
